version: "3.9"
  css-mysql:
    image: css/css-mysql
    ports:
      - 3307:3306
    networks:
      - css-network

css-app:
    image: pablogames/customer-subscription-service
    depends_on:
      - css-mysql
    environment:
    networks:
      - css-network
networks:
    css-network:
        driver: bridge

