version: '3.9'
services:
  css-mysql:
      image: pablogames/css-mysql:v1.1
      ports:
        - 3307:3306
      networks:
        - css-network
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  css-app:
      image: pablogames/customer-subscription-service
      ports:
        - 8080:8080
      depends_on:
        css-mysql:
          condition: service_healthy
      environment:
        - DATABASE_HOST=css-mysql
      networks:
        - css-network
networks:
      css-network:
          driver: bridge

