version: '3.9'
services:
  css-mysql:
      image: pablogames/css-mysql:firstimagepush
      ports:
        - 3307:3306
      networks:
        - css-network

  css-app:
      image: pablogames/customer-subscription-service
      depends_on:
        - css-mysql
      networks:
        - css-network
networks:
      css-network:
          driver: bridge

